
package Formularios;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emerson
 */
public class FrmModificarTarea extends javax.swing.JFrame {

  
    Tarea tarea = new Tarea();
    public FrmModificarTarea() {
        initComponents();
        setLocationRelativeTo(this);
        rsscalelabel.RSScaleLabel.setScaleLabel(fondo, "C:\\Users\\Emerson\\Documents\\NetBeansProjects\\Proyecto Organizador Al Fin\\Organizador\\src\\Imagenes\\24.jpg");
        
        tarea = EstadoGlobal.TransferenciaTarea;
        txtNuevoNombreTarea.setText(tarea.getNombre());
        txtNuevaDeTa.setText(tarea.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNuevoNombreTarea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Inicio = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        Fin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtNuevaDeTa = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        FondoTitulo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NUEVO NOMBRE");
        FondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, 25));

        txtNuevoNombreTarea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNuevoNombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoNombreTareaActionPerformed(evt);
            }
        });
        FondoPanel.add(txtNuevoNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 250, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("OPCIONAL");
        FondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("FECHA INICIO");
        FondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 20));
        FondoPanel.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 150, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FECHA FIN");
        FondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, 22));
        FondoPanel.add(Fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 150, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NUEVA DESCRIPCION");
        FondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 148, 30));

        txtNuevaDeTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaDeTaActionPerformed(evt);
            }
        });
        FondoPanel.add(txtNuevaDeTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 247, 71));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/save_norm.png"))); // NOI18N
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/vista_prev_press.png"))); // NOI18N
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/save_roll.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        FondoPanel.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/vista_prev_norm.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/vista_prev_press.png"))); // NOI18N
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/vista_prev_roll.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        FondoPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 100, 40));

        FondoTitulo.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MODIFICAR TAREA");

        javax.swing.GroupLayout FondoTituloLayout = new javax.swing.GroupLayout(FondoTitulo);
        FondoTitulo.setLayout(FondoTituloLayout);
        FondoTituloLayout.setHorizontalGroup(
            FondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
        );
        FondoTituloLayout.setVerticalGroup(
            FondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        FondoPanel.add(FondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/24.jpg"))); // NOI18N
        FondoPanel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            ListadoTareas listadoTareas = EstadoGlobal.TransferencialistadoTareas;
            String id = EstadoGlobal.TransferenciaTarea.getId();
            Date inicio = Inicio.getDate();
            Date fin = Fin.getDate();
            String nombre = txtNuevoNombreTarea.getText().trim().replaceAll("\\s*\\|\\s*", " pipe operator ");
            String descripcion = txtNuevaDeTa.getText().trim().replaceAll("\\s*\\|\\s*", " pipe operator ");
            String fechaInicio = "";
            String fechaFinal = "";
            if (inicio != null && fin != null) {
                fechaInicio = fecha.format(Inicio.getCalendar().getTime());
                fechaFinal = fecha.format(Fin.getCalendar().getTime());
            }
            if (!nombre.equals("") && !descripcion.equals("") && !nombre.isBlank() && !descripcion.isBlank() && !nombre.isEmpty() && !descripcion.isEmpty()) {               
                Tarea tarea = new Tarea();
                if (!fechaInicio.equals("") && !fechaFinal.equals("") && !fechaInicio.isBlank() && !fechaFinal.isBlank() && !fechaInicio.isEmpty() && !fechaFinal.isEmpty()) {
                    Date dt_1 = fecha.parse(fechaInicio);
                    Date dt_2 = fecha.parse(fechaFinal);
                    if (dt_1.compareTo(dt_2) > 0) {
                        JOptionPane.showMessageDialog(null, "La fecha inicio ocurre luego de la fecha final");
                    } // el método compareTo devuelve el valor mayor que 0 si esta Fecha está después del argumento Fecha.
                    else if (dt_1.compareTo(dt_2) < 0) {
                        listadoTareas.modificarListas(id, nombre,descripcion,fechaInicio,fechaFinal,"");
                        JOptionPane.showMessageDialog(null, "Tarea modificada exitosamente!");
                    } // el método compareTo devuelve el valor menor que 0 si esta Fecha es anterior al argumento Fecha;
                    else if (dt_1.compareTo(dt_2) == 0) {
                       listadoTareas.modificarListas(id, nombre,descripcion,fechaInicio,fechaFinal,"");
                       JOptionPane.showMessageDialog(null, "Tarea modificada exitosamente!");               
                    } // el método compareTo devuelve el valor 0 si el argumento Fecha es igual a la segunda Fecha;
                    else {
                        System.out.println("¡Pareces ser un viajero del tiempo!");
                    }

                }else{
                    tarea.setFechaInicio("sin datos");
                    tarea.setFechaFinal("sin datos");
                    tarea.setVigenciaToString("sin datos");
                    listadoTareas.modificarListas(id, nombre,descripcion,"sin datos","sin datos","sin datos");
                    JOptionPane.showMessageDialog(null, "Tarea modificada exitosamente!");  
                }
                txtNuevoNombreTarea.setText("");
                txtNuevaDeTa.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Llene todos los campos");
            }
        }catch(NumberFormatException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Error! " + ex);
            txtNuevoNombreTarea.setText("");
            txtNuevaDeTa.setText("");
        } catch (ParseException ex) {
            Logger.getLogger(FrmAgregarTarea.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        try {
            FrmTarea frm = new FrmTarea();
            frm.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(FrmModificarTarea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNuevaDeTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaDeTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaDeTaActionPerformed

    private void txtNuevoNombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoNombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoNombreTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fin;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JPanel FondoTitulo;
    private com.toedter.calendar.JDateChooser Inicio;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNuevaDeTa;
    private javax.swing.JTextField txtNuevoNombreTarea;
    // End of variables declaration//GEN-END:variables
}
